<?php include_partial('Common/header', ['displayBanner' => false]) ?>

  <div class="con_intro pv" id="intro">
    <div class="container">
      <div
        class="box_intro"
        style="margin: auto; width: auto !important;"
      >
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><strong><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>I - CH&Iacute;NH S&Aacute;CH V&Agrave; QUY ĐỊNH CHUNG</span></strong></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:red;'>Autosms.vn&nbsp;</span><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>l&agrave; website do&nbsp;</span><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:red;'>C&ocirc;ng ty Cổ phần Đầu tư v&agrave; C&ocirc;ng nghệ GHD&nbsp;</span><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>ph&aacute;t triển. Qu&yacute; kh&aacute;ch vui l&ograve;ng lưu &yacute; những quy định dưới đ&acirc;y khi sử dụng:</span></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>Ch&uacute;ng t&ocirc;i cam kết rằng mọi th&ocirc;ng tin v&agrave; dữ liệu li&ecirc;n quan tới sản phầm/ dịch vụ tại trang website:&nbsp;</span><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:red;'>autosms.vn</span><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>&nbsp;được cung cấp với mức độ tin cậy cao nhất nhằm gi&uacute;p kh&aacute;ch h&agrave;ng tra cứu, tham khảo, t&igrave;m hiểu v&agrave; định hướng th&ocirc;ng tin trước khi quyết định đăng k&yacute; dịch vụ. V&igrave; vậy, C&ocirc;ng ty GHD kh&ocirc;ng chịu bất cứ tr&aacute;ch nhiệm ph&aacute;p l&yacute; g&igrave; đối với bất kỳ ai li&ecirc;n quan đến việc sử dụng c&aacute;c th&ocirc;ng tin c&oacute; tr&ecirc;n website.</span></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>To&agrave;n bộ website v&agrave; c&aacute;c nội dung, th&ocirc;ng tin chi tiết cụ thể của website thuộc quyền sở hữu của C&ocirc;ng ty GHD, được bảo hộ theo ph&aacute;p luật của Nước CHXHCN Việt Nam. Tuỳ thuộc y&ecirc;u cầu hoạt động, C&ocirc;ng ty GHD c&oacute; thể điều chỉnh tổng thể việc sử dụng website hoặc c&aacute;c nội dung của website.&nbsp;</span></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>Người sử dụng phải tu&acirc;n theo những hướng dẫn v&agrave; chỉ dẫn sử dụng website&nbsp;</span><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:red;'>autosms.vn&nbsp;</span><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>một c&aacute;ch đầy đủ, đ&uacute;ng c&aacute;ch nhất v&agrave; kh&ocirc;ng c&oacute; bất kỳ h&agrave;nh vi n&agrave;o tr&aacute;i ph&aacute;p luật, tr&aacute;i đạo đức trong việc sử dụng website.</span><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>&nbsp;</span></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>Tất cả những kh&aacute;ch h&agrave;ng tham gia dịch vụ được coi l&agrave; đ&atilde; đọc, hiểu r&otilde;, đồng &yacute; v&agrave; tu&acirc;n thủ<strong>&nbsp;</strong>c&aacute;c quy định v&agrave; thể lệ của dịch vụ, đồng &yacute; với c&aacute;c Quy định được đặt ra một c&aacute;ch tự nguyện.</span></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><strong><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>II - QUY ĐỊNH V&Agrave; H&Igrave;NH THỨC THANH TO&Aacute;N</span></strong></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><strong><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>1.&nbsp;</span></strong><strong><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>Bảng gi&aacute;</span></strong></p>
        <table style="width:101.12%;background:white;border-collapse:collapse;border:none;">
          <tbody>
          <tr>
            <td style="width:28.35pt;border:solid windowtext 1.0pt;background:transparent;padding:0in 3.75pt 0in 3.75pt;height:17.0pt;">
              <p style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:  justify;'><strong><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>STT</span></strong></p>
            </td>
            <td style="width:219.5pt;border:solid windowtext 1.0pt;border-left:  none;background:transparent;padding:0in 3.75pt 0in 3.75pt;height:17.0pt;">
              <p style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:  justify;'><strong><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>Nội dung</span></strong></p>
            </td>
            <td style="width:208.0pt;border:solid windowtext 1.0pt;border-left:  none;background:transparent;padding:0in 3.75pt 0in 3.75pt;height:17.0pt;">
              <p style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:  justify;'><strong><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>Gi&aacute; cước</span></strong></p>
            </td>
          </tr>
          <tr>
            <td style="width:28.35pt;border:solid windowtext 1.0pt;border-top:  none;background:transparent;padding:0in 3.75pt 0in 3.75pt;height:17.0pt;">
              <p style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:  justify;'><span style='font-size:17px;line-height:107%;font-family:  "Times New Roman",serif;color:#1F3864;'>1</span></p>
            </td>
            <td style="width:219.5pt;border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;background:transparent;padding:0in 3.75pt 0in 3.75pt;height:17.0pt;">
              <p style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:  justify;'><span style='font-size:17px;line-height:107%;font-family:  "Times New Roman",serif;color:#1F3864;'>G&oacute;i ng&agrave;y</span></p>
            </td>
            <td style="width:208.0pt;border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;background:transparent;padding:0in 3.75pt 0in 3.75pt;height:17.0pt;">
              <p style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:  justify;'><span style='font-size:17px;line-height:107%;font-family:  "Times New Roman",serif;color:#1F3864;'>500đ/ngày, gia hạn h&agrave;ng ng&agrave;y</span></p>
            </td>
          </tr>
          <tr>
            <td style="width:28.35pt;border:solid windowtext 1.0pt;border-top:  none;background:transparent;padding:0in 3.75pt 0in 3.75pt;height:17.0pt;">
              <p style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:  justify;'><span style='font-size:17px;line-height:107%;font-family:  "Times New Roman",serif;color:#1F3864;'>2</span></p>
            </td>
            <td style="width:219.5pt;border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;background:transparent;padding:0in 3.75pt 0in 3.75pt;height:17.0pt;">
              <p style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:  justify;'><span style='font-size:17px;line-height:107%;font-family:  "Times New Roman",serif;color:#1F3864;'>G&oacute;i tuần</span></p>
            </td>
            <td style="width:208.0pt;border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;background:transparent;padding:0in 3.75pt 0in 3.75pt;height:17.0pt;">
              <p style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:  justify;'><span style='font-size:17px;line-height:107%;font-family:  "Times New Roman",serif;color:#1F3864;'>2.000đ/tuần, gia hạn h&agrave;ng tuần</span></p>
            </td>
          </tr>
          <tr>
            <td style="width:28.35pt;border:solid windowtext 1.0pt;border-top:  none;background:transparent;padding:0in 3.75pt 0in 3.75pt;height:17.0pt;">
              <p style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:  justify;'><span style='font-size:17px;line-height:107%;font-family:  "Times New Roman",serif;color:#1F3864;'>3</span></p>
            </td>
            <td style="width:219.5pt;border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;background:transparent;padding:0in 3.75pt 0in 3.75pt;height:17.0pt;">
              <p style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:  justify;'><span style='font-size:17px;line-height:107%;font-family:  "Times New Roman",serif;color:#1F3864;'>G&oacute;i th&aacute;ng</span></p>
            </td>
            <td style="width:208.0pt;border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;background:transparent;padding:0in 3.75pt 0in 3.75pt;height:17.0pt;">
              <p style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:  justify;'><span style='font-size:17px;line-height:107%;font-family:  "Times New Roman",serif;color:#1F3864;'>5.000đ/th&aacute;ng, gia hạn h&agrave;ng th&aacute;ng</span></p>
            </td>
          </tr>
          <tr>
            <td style="width:28.35pt;border:solid windowtext 1.0pt;border-top:  none;background:transparent;padding:0in 3.75pt 0in 3.75pt;height:17.0pt;">
              <p style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:  justify;'><span style='font-size:17px;line-height:107%;font-family:  "Times New Roman",serif;color:#1F3864;'>4</span></p>
            </td>
            <td style="width:219.5pt;border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;background:transparent;padding:0in 3.75pt 0in 3.75pt;height:17.0pt;">
              <p style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:  justify;'><span style='font-size:17px;line-height:107%;font-family:  "Times New Roman",serif;color:#1F3864;'>G&oacute;i b&aacute;o bận theo giờ</span></p>
            </td>
            <td style="width:208.0pt;border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;background:transparent;padding:0in 3.75pt 0in 3.75pt;height:17.0pt;">
              <p style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:  justify;'><span style='font-size:17px;line-height:107%;font-family:  "Times New Roman",serif;color:#1F3864;'>Miễn ph&iacute;</span></p>
            </td>
          </tr>
          <tr>
            <td style="width:28.35pt;border:solid windowtext 1.0pt;border-top:  none;background:transparent;padding:0in 3.75pt 0in 3.75pt;height:17.0pt;">
              <p style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:  justify;'><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>5</span></p>
            </td>
            <td style="width:219.5pt;border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;background:transparent;padding:0in 3.75pt 0in 3.75pt;height:17.0pt;">
              <p style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:  justify;'><span style='font-size:17px;line-height:107%;font-family:  "Times New Roman",serif;color:#1F3864;'>Cước Data</span></p>
            </td>
            <td style="width:208.0pt;border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;background:transparent;padding:0in 3.75pt 0in 3.75pt;height:17.0pt;">
              <p style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:  justify;'><span style='font-size:17px;line-height:107%;font-family:  "Times New Roman",serif;color:#1F3864;'>Miễn ph&iacute;</span></p>
            </td>
          </tr>
          <tr>
            <td style="width:28.35pt;border:solid windowtext 1.0pt;border-top:  none;background:transparent;padding:0in 3.75pt 0in 3.75pt;height:17.0pt;">
              <p style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:  justify;'><span style='font-size:17px;line-height:107%;font-family:  "Times New Roman",serif;color:#1F3864;'>6</span></p>
            </td>
            <td style="width:219.5pt;border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;background:transparent;padding:0in 3.75pt 0in 3.75pt;height:17.0pt;">
              <p style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:  justify;'><span style='font-size:17px;line-height:107%;font-family:  "Times New Roman",serif;color:#1F3864;'>Hủy dịch vụ</span></p>
            </td>
            <td style="width:208.0pt;border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;background:transparent;padding:0in 3.75pt 0in 3.75pt;height:17.0pt;">
              <p style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:  justify;'><span style='font-size:17px;line-height:107%;font-family:  "Times New Roman",serif;color:#1F3864;'>Miễn ph&iacute;</span></p>
            </td>
          </tr>
          <tr>
            <td style="width:28.35pt;border:solid windowtext 1.0pt;border-top:  none;background:transparent;padding:0in 3.75pt 0in 3.75pt;height:17.0pt;">
              <p style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:  justify;'><span style='font-size:17px;line-height:107%;font-family:  "Times New Roman",serif;color:#1F3864;'>7</span></p>
            </td>
            <td style="width:219.5pt;border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;background:transparent;padding:0in 3.75pt 0in 3.75pt;height:17.0pt;">
              <p style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:  justify;'><span style='font-size:17px;line-height:107%;font-family:  "Times New Roman",serif;color:#1F3864;'>C&aacute;c tin tương t&aacute;c kh&aacute;c</span></p>
            </td>
            <td style="width:208.0pt;border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;background:transparent;padding:0in 3.75pt 0in 3.75pt;height:17.0pt;">
              <p style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:  justify;'><span style='font-size:17px;line-height:107%;font-family:  "Times New Roman",serif;color:#1F3864;'>Miễn ph&iacute;</span></p>
            </td>
          </tr>
          </tbody>
        </table>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><strong><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>2. Quy tr&igrave;nh thanh to&aacute;n</span></strong></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>- Tổng đ&agrave;i autosms.vn l&agrave; tổng đ&agrave;i ghi nhận v&agrave; thực hiện trừ tiền theo c&aacute;c giao dịch được Kh&aacute;ch h&agrave;ng lựa chọn.</span></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>- Khi thực hiện lệnh &ldquo;Đăng k&yacute; g&oacute;i cước&rdquo; hệ thống sẽ căn cứ v&agrave;o c&aacute;c c&uacute; ph&aacute;p được nhập để tiến h&agrave;nh trừ tiền đối với từng giao dịch. Đối với thu&ecirc; bao trả trước, tổng đ&agrave;i sẽ kết nối với nh&agrave; mạng để x&aacute;c định khoản tiền cần trừ trực tiếp ngay tại thời điểm Kh&aacute;ch h&agrave;ng y&ecirc;u cầu lệnh. Đối với thu&ecirc; bao trả sau, hệ thống sẽ ghi nhận số tiền phải trả tr&ecirc;n t&agrave;i khoản điện thoại v&agrave; được ghi v&agrave;o h&oacute;a đơn cước của th&aacute;ng tương ứng.</span></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>- Số tiền bị trừ tương ứng với số lần giao dịch v&agrave; gi&aacute; của từng nội dung ni&ecirc;m yết c&ocirc;ng khai tr&ecirc;n website autosms.vn. Khoản tiền n&agrave;y sau khi nh&agrave; mạng thực hiện trừ sẽ được ho&agrave;n trả lại cho autosms.vn.</span></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><strong><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>3</span></strong><strong><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>. Đảm bảo an to&agrave;n giao dịch</span></strong></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>- Đảm bảo an to&agrave;n thanh to&aacute;n:</span></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>Autosms.vn sử dụng c&aacute;c dịch vụ, hệ thống thanh to&aacute;n t&iacute;ch hợp nhiều t&iacute;nh năng th&ocirc;ng minh, chế độ bảo mật cao để đảm bảo th&ocirc;ng tin c&aacute; nh&acirc;n, đảm bảo an to&agrave;n thanh to&aacute;n của Kh&aacute;ch h&agrave;ng. Autosms.vn sẽ kh&ocirc;ng t&iacute;nh tiền cho đến khi giao dịch được ho&agrave;n tất.</span></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>Việc thanh to&aacute;n dựa tr&ecirc;n cơ chế trừ tiền của mạng viễn th&ocirc;ng n&ecirc;n lu&ocirc;n đảm bảo độ ch&iacute;nh x&aacute;c cao nhất.</span></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><strong><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>III - CH&Iacute;NH S&Aacute;CH GIAO NHẬN, BẢO H&Agrave;NH, ĐỔI TRẢ V&Agrave; HO&Agrave;N TIỀN</span></strong></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>- Khi hệ thống nhận được lệnh đăng k&yacute; hợp lệ, hệ thống sẽ ngay lập tức ghi nhận ch&iacute;nh s&aacute;ch thu&ecirc; bao được hưởng tr&ecirc;n dịch vụ hoặc gửi nội dung Kh&aacute;ch h&agrave;ng đ&atilde; mua về thiết bị của Kh&aacute;ch h&agrave;ng.</span></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>- Autosms.vn kh&ocirc;ng &aacute;p dụng ch&iacute;nh s&aacute;ch bảo h&agrave;nh, đổi trả sản phẩm khi nội dung đ&atilde; được chuyển đến thiết bị của kh&aacute;ch h&agrave;ng th&agrave;nh c&ocirc;ng.</span></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>- Tất cả c&aacute;c giao dịch đ&atilde; nhận được th&ocirc;ng b&aacute;o th&agrave;nh c&ocirc;ng đều kh&ocirc;ng được ho&agrave;n trả ph&iacute; từ hệ thống trong mọi trường hợp.</span></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>- Trong trường hợp giao dịch lỗi, hệ thống đ&atilde; tiến h&agrave;nh trừ tiền th&agrave;nh c&ocirc;ng trong t&agrave;i khoản của kh&aacute;ch h&agrave;ng m&agrave; kh&aacute;ch h&agrave;ng kh&ocirc;ng nhận được nội dung m&igrave;nh đ&atilde; mua hoặc kh&ocirc;ng sử dụng được ch&iacute;nh s&aacute;ch m&agrave; thu&ecirc; bao được hưởng theo g&oacute;i cước đ&atilde; đăng k&yacute;, hệ thống sẽ gửi lại nội dung hoặc b&ugrave; lại số ng&agrave;y sử dụng cho kh&aacute;ch h&agrave;ng tương ứng với nội dung bị lỗi hoặc số ng&agrave;y bị gi&aacute;n đoạn sử dụng.</span></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><strong><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>IV - CH&Iacute;NH S&Aacute;CH BẢO VỆ TH&Ocirc;NG TIN C&Aacute; NH&Acirc;N CỦA KH&Aacute;CH H&Agrave;NG</span></strong></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>- Mọi sự thu thập th&ocirc;ng tin v&agrave; sử dụng th&ocirc;ng tin của Kh&aacute;ch h&agrave;ng đều được th&ocirc;ng qua &yacute; kiến của ch&iacute;nh Kh&aacute;ch h&agrave;ng đ&oacute; trước khi Kh&aacute;ch h&agrave;ng tiến h&agrave;nh c&aacute;c giao dịch cụ thể. Việc bảo vệ th&ocirc;ng tin c&aacute; nh&acirc;n Kh&aacute;ch h&agrave;ng được thực hiện theo đ&uacute;ng nguy&ecirc;n tắc sau:</span></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><strong><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>a. Mục đ&iacute;ch thu thập th&ocirc;ng tin c&aacute; nh&acirc;n</span></strong></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>- Thực hiện c&aacute;c giao dịch theo c&aacute;c đơn đặt h&agrave;ng của Kh&aacute;ch h&agrave;ng, giới thiệu về dịch vụ, t&iacute;nh năng mới của website autosms.vn, chăm s&oacute;c Kh&aacute;ch h&agrave;ng.</span></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>- T&iacute;nh gi&aacute;, cước sử dụng.</span></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>- Quản l&yacute; về giao dịch y&ecirc;u cầu thực hiện</span></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>- Giải quyết c&aacute;c thắc mắc hay khiếu nại ph&aacute;t sinh khi Kh&aacute;ch h&agrave;ng sử dụng dịch vụ autosms.vn.</span></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>- Ngăn chặn những hoạt động vi phạm ph&aacute;p luật tại website autosms.vn.</span></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><strong><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>b. Phạm vi sử dụng th&ocirc;ng tin</span></strong></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>- Chỉ sử dụng c&aacute;c th&ocirc;ng tin được kh&aacute;ch h&agrave;ng đăng k&yacute; hoặc cập nhật tr&ecirc;n website autosms.vn, kh&ocirc;ng sử dụng c&aacute;c th&ocirc;ng tin do kh&aacute;ch h&agrave;ng đưa tr&ecirc;n c&aacute;c phương tiện, c&ocirc;ng cụ kh&aacute;c.</span></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>- Khi cần thiết, ch&uacute;ng t&ocirc;i c&oacute; thể sử dụng những th&ocirc;ng tin n&agrave;y để li&ecirc;n hệ trực tiếp với kh&aacute;ch h&agrave;ng để th&ocirc;ng b&aacute;o về: th&ocirc;ng tin về khuyến m&atilde;i v&agrave; dịch vụ mới, li&ecirc;n lạc v&agrave; giải quyết với kh&aacute;ch h&agrave;ng những trường hợp đặc biệt&hellip;</span></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>- Kh&ocirc;ng sử dụng số điện thoại của kh&aacute;ch h&agrave;ng ngo&agrave;i mục đ&iacute;ch x&aacute;c nhận v&agrave; li&ecirc;n hệ c&oacute; li&ecirc;n quan đến dịch vụ m&agrave; kh&aacute;ch h&agrave;ng đăng k&yacute; sử dụng của c&ocirc;ng ty.</span></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><strong><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>c. Thời gian lưu trữ th&ocirc;ng tin: 05 năm</span></strong></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><strong><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>d. Những người, tổ chức c&oacute; thể tiếp cận th&ocirc;ng tin đ&atilde; thu thập bao gồm:</span></strong></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>- Đơn vị chủ quản website autosms.vn.</span></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>- Đơn vị viễn th&ocirc;ng khi thực hiện trừ gi&aacute; cước sử dụng.</span></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>- Cơ quan nh&agrave; nước c&oacute; thẩm quyền khi c&oacute; y&ecirc;u cầu cụ thể.</span></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><strong><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>e. Địa chỉ của đơn vị thu thập v&agrave; quản l&yacute; th&ocirc;ng tin</span></strong></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>C&Ocirc;NG TY CỔ PHẦN ĐẦU TƯ V&Agrave; C&Ocirc;NG NGHỆ GHD</span></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>Địa chỉ: Số 19D, ng&otilde; 27 phố V&otilde;ng Thị, phường Bưởi, quận T&acirc;y Hồ, Th&agrave;nh phố H&agrave; Nội</span></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>Điện thoại: 024</span><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>.</span><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>6</span><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>281.1919</span></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>Email:&nbsp;</span><a href="mailto:contact@ghdc.vn"><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;'>contact@ghdc.vn</span></a><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>&nbsp;</span></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><strong><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>f</span></strong><strong><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>. Phương thức v&agrave; c&ocirc;ng cụ để người ti&ecirc;u d&ugrave;ng tiếp cận v&agrave; chỉnh sửa dữ liệu c&aacute; nh&acirc;n của m&igrave;nh tr&ecirc;n hệ thống thương mại điện tử của đơn vị thu thập th&ocirc;ng tin</span></strong></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>- Người d&ugrave;ng c&oacute; thể tiếp cận th&ocirc;ng tin c&aacute; nh&acirc;n (cụ thể l&agrave; số điện thoại của m&igrave;nh) bằng c&aacute;ch truy cập v&agrave;o website dịch vụ autosms.vn, v&agrave;o mục T&agrave;i khoản để biết được kh&aacute;ch h&agrave;ng c&oacute; đăng k&yacute; dịch vụ hay kh&ocirc;ng.</span></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>- Về phần chỉnh sửa dữ liệu c&aacute; nh&acirc;n: kh&aacute;ch h&agrave;ng kh&ocirc;ng ch&iacute;nh sử được số điện thoại v&igrave; khi kh&aacute;ch h&agrave;ng đăng k&yacute; dịch vụ th&igrave; hệ thống sẽ nhận biết số điện thoại của kh&aacute;ch h&agrave;ng.</span></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><strong><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>g. Cơ chế tiếp nhận v&agrave; giải quyết khiếu nại của người ti&ecirc;u d&ugrave;ng li&ecirc;n quan đến việc th&ocirc;ng tin c&aacute; nh&acirc;n bị sử dụng sai mục đ&iacute;ch hoặc phạm vi đ&atilde; th&ocirc;ng b&aacute;o</span></strong></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>Khi phát hi&ecirc;̣n th&ocirc;ng tin cá nh&acirc;n (cụ thể số điện thoại) của mình bị sử dụng sai mục đích hoặc phạm vi, người dùng có quy&ecirc;̀n gọi đến Tổng đ&agrave;i chăm s&oacute;c kh&aacute;ch h&agrave;ng: 1900.96.96.91 hoặc gửi email khiếu nại đ&ecirc;́n&nbsp;</span><a href="mailto:cskh@ghdc.vn"><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;'>cskh@ghdc.vn</span></a><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>&nbsp;với các th&ocirc;ng tin, chứng cứ li&ecirc;n quan tới vi&ecirc;̣c này. C&ocirc;ng ty cam k&ecirc;́t sẽ phản h&ocirc;̀i ngay l&acirc;̣p tức trong vòng 24 ti&ecirc;́ng đ&ecirc;̉ cùng kh&aacute;ch h&agrave;ng th&ocirc;́ng nh&acirc;́t phương án giải quy&ecirc;́t.</span></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><strong><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>h. Cam kết bảo mật th&ocirc;ng tin c&aacute; nh&acirc;n của Kh&aacute;ch h&agrave;ng</span></strong></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>- Th&ocirc;ng tin c&aacute; nh&acirc;n của kh&aacute;ch h&agrave;ng tr&ecirc;n autosms.vn được autosms.vn cam kết bảo mật tuyệt đối theo ch&iacute;nh s&aacute;ch bảo vệ th&ocirc;ng tin c&aacute; nh&acirc;n của autosms.vn.Việc thu thập v&agrave; sử dụng th&ocirc;ng tin của mỗi kh&aacute;ch h&agrave;ng chỉ được thực hiện khi c&oacute; sự đồng &yacute; của kh&aacute;ch h&agrave;ng đ&oacute; trừ những trường hợp ph&aacute;p luật c&oacute; quy định kh&aacute;c;</span></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>- Kh&ocirc;ng sử dụng, kh&ocirc;ng chuyển giao, cung cấp hay tiết lộ cho b&ecirc;n thứ 3 n&agrave;o về th&ocirc;ng tin c&aacute; nh&acirc;n của Kh&aacute;ch h&agrave;ng khi kh&ocirc;ng c&oacute; sự cho ph&eacute;p đồng &yacute; từ kh&aacute;ch h&agrave;ng;</span></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>- Trong trường hợp m&aacute;y chủ lưu trữ th&ocirc;ng tin bị hacker tấn c&ocirc;ng dẫn đến mất m&aacute;t dữ liệu c&aacute; nh&acirc;n kh&aacute;ch h&agrave;ng, autosms.vn sẽ c&oacute; tr&aacute;ch nhiệm th&ocirc;ng b&aacute;o vụ việc cho cơ quan chức năng điều tra xử l&yacute; kịp thời v&agrave; th&ocirc;ng b&aacute;o cho Kh&aacute;ch h&agrave;ng được biết;</span></p>
        <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;'><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;color:#1F3864;'>- Tuy nhi&ecirc;n do hạn chế về mặt kỹ thuật, kh&ocirc;ng một dữ liệu n&agrave;o c&oacute; thể được truyền tr&ecirc;n đường truyền internet m&agrave; c&oacute; thể được bảo mật 100%. Do vậy, autosms.vn kh&ocirc;ng thể đưa ra một cam kết chắc chắn rằng th&ocirc;ng tin Kh&aacute;ch h&agrave;ng cung cấp cho autosms.vn sẽ được bảo mật một c&aacute;ch tuyệt đối an to&agrave;n, v&agrave; autosms.vn kh&ocirc;ng thể chịu tr&aacute;ch nhiệm trong trường hợp c&oacute; sự truy cập tr&aacute;i ph&eacute;p th&ocirc;ng tin c&aacute; nh&acirc;n của Kh&aacute;ch h&agrave;ng, như c&aacute;c trường hợp kh&aacute;ch h&agrave;ng tự &yacute; chia sẻ th&ocirc;ng tin với người kh&aacute;c.</span></p>
      </div>
    </div>
  </div>
