# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
#    charset: utf-8
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:
    - font-awesome.min.css
    - https://fonts.googleapis.com/css?family=Open+Sans|Roboto
    - bootstrap.min.css
    - slick.css
    - default.css
    - common.css
    - homepage.css
  javascripts:
    - slick.min.js
    - common.js
  has_layout:     true
  layout:         layout
