## YAML Template.
---
indexSuccess:
  metas:
    title: Trang chủ
createSuccess:
  metas:
    title: Tạo lịch gửi tin
  stylesheets:
    - /datetimepicker/DateTimePicker.css
  javascripts:
    - /datetimepicker/DateTimePicker.js
    - /datetimepicker/i18n/DateTimePicker-i18n.js
    - datetimepicker.js?v=1.5
    - main.js?v=1.5
detailSuccess:
  metas:
    title: Thông tin lịch gửi tin
  javascripts:
    - main.js?v=1.5
mpsResultSuccess:
  metas:
    title: Kết quả thanh toán