## YAML Template.
---
indexSuccess:
  metas:
    title: Trang chủ
  stylesheets:
    - app.css
createSuccess:
  metas:
    title: Tạo lịch gửi tin
  stylesheets:
    - https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css: {integrity: sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T, crossorigin: anonymous}
    - /datetimepicker/DateTimePicker.css
    - app2.css
  javascripts:
    - /datetimepicker/DateTimePicker.js
    - /datetimepicker/i18n/DateTimePicker-i18n.js
    - datetimepicker.js?v=1.3
    - main.js
detailSuccess:
  metas:
    title: Thông tin lịch gửi tin
  stylesheets:
    - https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css: {integrity: sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T, crossorigin: anonymous}
    - app2.css
  javascripts:
    - main.js
mpsResultSuccess:
  metas:
    title: Kết quả thanh toán
  stylesheets:
    - https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css: {integrity: sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T, crossorigin: anonymous}
    - app2.css