all:
  pattern_password: '/^\S*(?=\S{8,})(?=\S*\d)(?=\S*\W+)(?![.\n])(?=\S*[a-zA-Z])\S*$/'
  pattern_username: '/^([a-zA-Z])+([a-zA-Z0-9_]){5,29}$/'
#  mps_url: 'http://vas.vietteltelecom.vn/MPS/'
  mps_url: 'http://125.235.4.194/test/'
  ws_autosms:
    url: http://171.244.9.242:8280/kkk
    username: viettel
    password: jsKk432Sw